config/routes.rb
Rio::Application.routes.draw do
  resources :user_artikelgroeps
  resources :artikelgroeps
  resources :artikels
  resources :users do
    member do
      get :artikelgroeps
      get :new_artikelgroep
      get :orders
      get :new_order
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/orders/artikel_selectie', to: 'orders#artikel_selectie', via: 'get'
  resources :orders
  root 'static_pages#home'

end

app/models/user_artikelgroep.rb
class UserArtikelgroep < ActiveRecord::Base
  belongs_to :user
  belongs_to :artikelgroep

  validates_presence_of :user, message: " onbekend"
  validates_presence_of :artikelgroep, message: " onbekend"

  validates_uniqueness_of :artikelgroep_id, :scope => :user_id, message: " al bij user aanwezig"

  delegate :groepcode, to: :artikelgroep, prefix: :ag
  delegate :name, to: :user, prefix: :usr

def crud
  xa=[(auth_c)? "C":" ", (auth_r)? "R":" ", (auth_r)? "U":" ", (auth_d)? "D":" "]
  xa.join
end

end

app/controllers/user_artikelgroeps_controller.rb
class UserArtikelgroepsController < ApplicationController
  before_action :user_is_admin
  before_action :set_user_artikelgroep, only: [:show, :edit, :update, :destroy]

  # GET /user_artikelgroeps
  # GET /user_artikelgroeps.json
  def index
    @user_artikelgroeps = UserArtikelgroep.all
  end

  # GET /user_artikelgroeps/1
  # GET /user_artikelgroeps/1.json
  def show
  end

  # GET /user_artikelgroeps/new
  def new
    @user_artikelgroep = UserArtikelgroep.new
  end

  # GET /user_artikelgroeps/1/edit
  def edit
  end

  # POST /user_artikelgroeps
  # POST /user_artikelgroeps.json
  def create

    @user_artikelgroep = UserArtikelgroep.new(user_artikelgroep_params)

    @user_artikelgroep.user_id ||= $rio_user_id #backup for user_id

    respond_to do |format|
      if @user_artikelgroep.save
        if mode1?($rio_mode) ##started from a specific user
          format.html { redirect_to artikelgroeps_user_path($rio_user_id), notice: 'User artikelgroep was successfully created.' }
        else
          format.html { redirect_to @user_artikelgroep, notice: 'User artikelgroep was successfully created.' }
        end
        format.json { render action: 'show', status: :created, location: @user_artikelgroep }
      else
        format.html { render action: 'new' } #when something goes wrong it is not too bad to go to new
        format.json { render json: @user_artikelgroep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_artikelgroeps/1
  # PATCH/PUT /user_artikelgroeps/1.json
  def update
    #always current user id
    #  @user_artikelgroep.user_id=current_user.id

    respond_to do |format|
      if @user_artikelgroep.update(user_artikelgroep_params)
        if mode1?($rio_mode) ##started from a specific user
          format.html { redirect_to artikelgroeps_user_path(@user_artikelgroep.user_id), notice: 'User artikelgroep was successfully created.' }
        else
          format.html { redirect_to @user_artikelgroep, notice: 'User artikelgroep was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_artikelgroep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_artikelgroeps/1
  # DELETE /user_artikelgroeps/1.json
  def destroy
    $rio_user_id=@user_artikelgroep.user_id
    @user_artikelgroep.destroy
    respond_to do |format|
      if mode1?($rio_mode) ##started from a specific user
        format.html { redirect_to artikelgroeps_user_path($rio_user_id) }
      else
        format.html { redirect_to user_artikelgroeps_url }
      end
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user_artikelgroep
    @user_artikelgroep = UserArtikelgroep.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_artikelgroep_params
    params.require(:user_artikelgroep).permit(:user_id, :artikelgroep_id, :auth_c, :auth_r, :auth_u, :auth_d)
  end

  def mode1?(inpval)
    inpval == 1
    #   true
  end
end

app/helpers/user_artikelgroeps_helper.rb
module UserArtikelgroepsHelper

end

app/views/user_artikelgroeps/_form.html.erb
<%= form_for(@user_artikelgroep) do |f| %>
    <% if @user_artikelgroep.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_artikelgroep.errors.count, "error") %> prohibited this user_artikelgroep from being
            saved:</h2>

          <ul>
            <% @user_artikelgroep.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :user_id %>
      <br>
      <% if !@user_artikelgroep.user_id.nil? %>
          <%= @user_artikelgroep.usr_name %>
      <% else %>
          <%= f.text_field :user_id %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :artikelgroep_id %>
      <br>
      <% if !@user_artikelgroep.artikelgroep_id.nil? %>
          <%= @user_artikelgroep.ag_groepcode %>
      <% else %>
          <%= f.collection_select(:artikelgroep_id, Artikelgroep.all, :id, :omschrijving) %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :auth_c, "Create" %>
      <br>
      <%= f.check_box :auth_c %>
    </div>
    <div class="field">
      <%= f.label :auth_r, "Read" %>
      <br>
      <%= f.check_box :auth_r %>
    </div>
    <div class="field">
      <%= f.label :auth_u, "Update" %>
      <br>
      <%= f.check_box :auth_u %>
    </div>
    <div class="field">
      <%= f.label :auth_d, "Delete" %>
      <br>
      <%= f.check_box :auth_d %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/user_artikelgroeps/edit.html.erb
<h1>Editing user_artikelgroep</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_artikelgroep %> |
<%= link_to 'Back', :back    %>

app/views/user_artikelgroeps/index.html.erb
<h1>User artikelgroepen</h1>
<% $rio_mode = 0 %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Artikelgroep</th>
      <th>Auth c</th>
      <th>Auth r</th>
      <th>Auth u</th>
      <th>Auth d</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_artikelgroeps.each do |user_artikelgroep| %>
      <tr>
        <td><%= user_artikelgroep.usr_name %></td>
        <td><%= user_artikelgroep.ag_groepcode %></td>
        <td><%= user_artikelgroep.auth_c %></td>
        <td><%= user_artikelgroep.auth_r %></td>
        <td><%= user_artikelgroep.auth_u %></td>
        <td><%= user_artikelgroep.auth_d %></td>
        <td><%= link_to 'Show', user_artikelgroep %></td>
        <td><%= link_to 'Edit', edit_user_artikelgroep_path(user_artikelgroep) %></td>
        <td><%= link_to 'Destroy', user_artikelgroep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User artikelgroep', new_user_artikelgroep_path %>

app/views/user_artikelgroeps/new.html.erb
<h1>New user_artikelgroep</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/user_artikelgroeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_artikelgroep.usr_name %>
</p>

<p>
  <strong>Artikelgroep:</strong>
  <%= @user_artikelgroep.ag_groepcode %>
</p>

<p>
  <strong>Auth c:</strong>
  <%= @user_artikelgroep.auth_c %>
</p>

<p>
  <strong>Auth r:</strong>
  <%= @user_artikelgroep.auth_r %>
</p>

<p>
  <strong>Auth u:</strong>
  <%= @user_artikelgroep.auth_u %>
</p>

<p>
  <strong>Auth d:</strong>
  <%= @user_artikelgroep.auth_d %>
</p>

<%= link_to 'Edit', edit_user_artikelgroep_path(@user_artikelgroep) %> |
<% if $rio_mode == 1 %>
    <%= link_to 'Back',artikelgroeps_user_path(current_user.id) %>
<% else %>
    <%= link_to 'Back', user_artikelgroeps_path %>
<% end %>