config/routes.rb
Rio::Application.routes.draw do
  resources :user_artikelgroeps
  resources :artikelgroeps
  resources :artikels
  resources :users do
    member do
      get :artikelgroeps
      get :new_artikelgroep
      get :orders
      get :new_order
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/orders/artikel_selectie', to: 'orders#artikel_selectie', via: 'get'
  resources :orders
  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_artikelgroeps, foreign_key: "user_id", dependent: :destroy
#  has_many :artikels, :through => :user_artikelgroeps
  has_many :orders
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, unless: :new
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def edit
    #   @user = User.find(params[:id])      , not necessary
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
#    @users = User.all
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @user_artikelgroeps = @user.user_artikelgroeps
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def artikelgroeps
    @user = User.find(params[:id])
    @title = "Artikelgroepen van " + @user.name
    @user_ags = @user.user_artikelgroeps
    $rio_mode = 1
  end

  def new_artikelgroep
    @user = User.find(params[:id])
    @title = "Nieuwe artikelgroep voor " + @user.name
    @user_artikelgroep =@user.user_artikelgroeps.build #create relation with user
    $rio_mode = 1
    $rio_user_id = @user.id
  end

  def orders
    @user = User.find(params[:id])
    @title = "Orders van " + @user.name
    @orders = @user.orders
    $rio_mode = 1
  end

  def new_order
    @user = User.find(params[:id])
    @title = "Nieuwe order voor " + @user.name
    @order=@user.orders.build #create relation with user
    $rio_mode = 1
    $rio_user_id = @user.id
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless (current_user?(@user) || current_user.admin?)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end


end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def rio_number_of_groeps (user)
    cnt= user.user_artikelgroeps.count +1
    "Artikelgroepen(" << cnt << ")"
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if signed_in? %>
      <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"} %>
      <% end %>
  <% end %>
</li>

app/views/users/artikelgroeps.html.erb
<% provide(:title, @title) %>
<h2>Artikelgroepen van <%= @user.name %> </h2>

<table>
  <thead>
  <tr>
    <th>Artikelgroep</th>
    <th>Create</th>
    <th>Read</th>
    <th>Update</th>
    <th>Delete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @user_ags.each do |uag| %>
      <tr>
        <td><%= uag.ag_groepcode %></td>
        <td><%= uag.auth_c %></td>
        <td><%= uag.auth_r %></td>
        <td><%= uag.auth_u %></td>
        <td><%= uag.auth_d %></td>
        <td><%= link_to 'Show', uag %></td>
        <td><%= link_to 'Edit', edit_user_artikelgroep_path(uag) %></td>
        <td><%= link_to 'Destroy', uag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New User artikelgroep', new_artikelgroep_user_path %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        <% end %>

        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails">change</a>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new_artikelgroep.html.erb
<% provide(:title, @title) %>
<h2>Nieuwe artikelgroep voor <%= @user.name %> </h2>

<%= form_for(@user_artikelgroep) do |f| %>
    <% if @user_artikelgroep.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_artikelgroep.errors.count, "error") %> prohibited this user_artikelgroep from being
            saved:</h2>

          <ul>
            <% @user_artikelgroep.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :user_id %>
      <br>
      <%= @user_artikelgroep.usr_name %>
    </div>
    <div class="field">
      <%= f.label :artikelgroep_id %>
      <br>
      <%= f.collection_select(:artikelgroep_id, Artikelgroep.not_yet_assigned_to(@user.id), :id, :omschrijving) %> </br>
    </div>
    <div class="field">
      <%= f.label :auth_c, "Create" %>
      <br>
      <%= f.check_box :auth_c %>
    </div>
    <div class="field">
      <%= f.label :auth_r, "Read" %>
      <br>
      <%= f.check_box :auth_r %>
    </div>
    <div class="field">
      <%= f.label :auth_u, "Update" %>
      <br>
      <%= f.check_box :auth_u %>
    </div>
    <div class="field">
      <%= f.label :auth_d, "Delete" %>
      <br>
      <%= f.check_box :auth_d %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/new_order.html.erb
<% provide(:title, @title) %>
<h2>Nieuwe order voor <%= @user.name %> </h2>

<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being
            saved:</h2>

          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :user_id %>
      <br>
      <%= @user.name %>
    </div>
    <div class="field">
      <%= f.label :ordernr %>
      <br>
      <%= f.text_field :ordernr %> </br>
    </div>
    <div class="field">
      <%= f.label :opmerking %>
      <br>
      <%= f.text_field :opmerking %> </br>
    </div>    <div class="actions">
      <%= f.submit %>
    </div>

    <% if $rio_mode == 1 %>
        <%= link_to 'Back', orders_user_path(current_user.id) %>
    <% else %>
        <%= link_to 'Back', orders_path %>
    <% end %>
<% end %>

app/views/users/orders.html.erb
<% provide(:title, @title) %>
<h2>Orders van <%= @user.name %> </h2>

<table>
  <thead>
  <tr>
    <th>Ordernr</th>
    <th>Opmerking</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.ordernr %></td>
        <td><%= order.opmerking%></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Nieuwe order', new_order_user_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <%= link_to  artikelgroeps_user_path do %>
        <strong>Artikelgroepen (<%= @user.user_artikelgroeps.count %>)</strong>
    <% end %>  </br>
    <%= link_to  orders_user_path do %>
        <strong>Orders (<%= @user.orders.count %>)</strong>
    <% end %>
    </br></br>
    <% if signed_in? %>
    <%= user_is_admin? ? "Admin" : "geen admin" %>
    <% end %>
  </aside>
</div>