config/routes.rb
Rio::Application.routes.draw do
  resources :user_artikelgroeps
  resources :artikelgroeps
  resources :artikels
  resources :users do
    member do
      get :artikelgroeps
      get :new_artikelgroep
      get :orders
      get :new_order
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/orders/artikel_selectie', to: 'orders#artikel_selectie', via: 'get'
  resources :orders
  root 'static_pages#home'

end

app/models/artikel.rb
#require "#{Rails.root}/lib/validators/artikel_validator.rb"
class Artikel < ActiveRecord::Base
  belongs_to :artikelgroep
  has_many :order_regels

  validates :artikelnummer, presence: true, uniqueness: true
  # validates :artikelgroep_id, presence: true
  validates_presence_of :prijs, :message => " mag niet leeg zijn"
  validates :omschrijving, presence: true
  validates_presence_of :artikelgroep, message: " onbekend"

  validates_with ArtikelValidator

  delegate :groepcode, to: :artikelgroep
  delegate :omschrijving, to: :artikelgroep, prefix: :ag

# zie ook: http://stackoverflow.com/questions/5597347/rails-3-custom-validator-problem

end

app/controllers/artikels_controller.rb
class ArtikelsController < ApplicationController
  include ArtikelsHelper
  before_action :signed_in_user
  before_action :artikel_crud_create, only: :create
  before_action :artikel_crud_read, only: :show
  before_action :artikel_crud_update, only: :update
  before_action :artikel_crud_edit, only: :edit
  before_action :artikel_crud_delete, only: :delete
# check on create in create-action it self

  def new
    @artikel=Artikel.new
  end

  def index
    if params[:search]
      @artikels=Artikel.joins(artikels_current_user_search(params[:search]))
    else
      @artikels=Artikel.joins(artikels_current_user)
    end
  end

  def show
    @artikel = Artikel.find(params[:id])
  end

  def create
    @artikel = Artikel.new(artikel_params)
    if @artikel.save
      flash[:success] = "Artikel aangemaakt"
      redirect_to artikels_url # not to artikel @artikel, user may not have rights to show option
    else
      render 'new'
    end
  end

  def update
    @artikel = Artikel.find(params[:id])
    if @artikel.update_attributes(artikel_params)
      flash[:success] = "Artikel geupdeet"
      redirect_to artikels_url
    else
      render 'edit'
    end
  end

  def edit
    @artikel = Artikel.find(params[:id])

  end

  #DELETE
  def destroy
    @artikel = Artikel.find(params[:id])
    @artikel.destroy
    flash[:success] = "Artikel verwijderd"
    respond_to do |format|
      format.html { redirect_to artikels_url }
      format.json { head :no_content }
    end
  end

  private

  def artikel_crud
    @artikel = Artikel.find(params[:id])
    crud_current_user(@artikel.artikelgroep_id)
  end


  def artikel_crud_create
    #check authorisation of new artikelgroep
    if !crud_current_user(params[:artikel][:artikelgroep_id]).include? 'C'
      flash[:error] = "Create Autorisatie??"
      redirect_to artikels_url
    end
  end


  def artikel_crud_read #one of the options
    if !artikel_crud.include? 'R'
      flash[:error] = "Read Autorisatie??"
      redirect_to artikels_url
    end
  end

  def artikel_crud_edit
    #check authorisation of new artikelgroep
    if !artikel_crud.include? 'U'
      flash[:error] = "edit Autorisatie??"
      redirect_to artikels_url
    end
  end

  def artikel_crud_update
    #check authorisation of new artikelgroep
    if !crud_current_user(params[:artikel][:artikelgroep_id]).include? 'U'
      flash[:error] = "Update Autorisatie??"
      redirect_to artikels_url
    end
  end

  def artikel_crud_delete
    artikel_crud
    if !artikel_crud.include? 'D'
      flash[:error] = "Autorisatie??"
      redirect_to artikels_url
    end
  end

  def artikel_params
    params.require(:artikel).permit(:artikelnummer, :omschrijving, :prijs,
                                    :opmerking, :artikelgroep_id)
  end
end

app/helpers/artikels_helper.rb
module ArtikelsHelper

  def artikels_current_user #base for the artikel.join
    artikel_join= "JOIN user_artikelgroeps ua ON ua.artikelgroep_id=artikels.artikelgroep_id
    WHERE (ua.auth_c OR ua.auth_r OR ua.auth_u OR ua.auth_d) AND ua.user_id= "
    "#{artikel_join} #{current_user.id}"
  end

  def artikels_current_user_search(srcval) #base for the artikel.search
    artikel_like= [' AND artikels.omschrijving LIKE "%',srcval,'%"'].join

    artikels_join=artikels_current_user
    "#{artikels_join} #{artikel_like}"
  end

  def crud_current_user(ag_id) #get CRUD by a Artikelgroep
    ua=UserArtikelgroep.where("user_id = :uid AND artikelgroep_id= :ag_id", uid: current_user.id, ag_id: ag_id).first # first and only record
    if !ua.nil?
      ua.crud
    else
      " "
    end
  end

  def user_has_any_create_artikel #must be changed, use ORM
    sel1= "SELECT count(1) FROM user_artikelgroeps ua
    WHERE ua.auth_c = 1 AND ua.user_id= "
    sqlstr= "#{sel1}  #{current_user.id}"
    crudarr=ActiveRecord::Base.connection.execute(sqlstr).first
    (crudarr[0] > 0) ? true : false
  end


  def user_may_update_artikel (id)
    aa=crud_current_user (id)
    if !aa.include? 'U'
      false
    else
      true
    end
  end

  def user_may_see_artikel (id)
    aa=artikel_crud_current_user (id)
    if aa.blank?
      false
    else
      true
    end
  end

  def user_may_delete_artikel (id)
    aa=artikel_crud_current_user (id)
    if !aa.include? 'D'
      false
    else
      true
    end
  end

end

app/views/artikels/_form.html.erb
<%= form_for(@artikel) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.label t :artikelnummer %>
      <%= f.text_field :artikelnummer, :class => "size10 " %>
    </div>
    <div id="artikel_error"></div>
    <div class="field">
      <%= f.label t :prijs %>
      <%= f.text_field :prijs, :class => "size10", :value => number_to_currency(f.object.prijs, :unit => '') %>
    </div>
    <div class="field">
      <%= f.label t :omschrijving %>
      <%= f.text_field :omschrijving, :class => "size20" %>
    </div>
    <div class="field">
      <%= f.label t :opmerking %>
      <%= f.text_field :opmerking %>
    </div>
    <div class="field">
      <%= f.label t :artikelgroep_id %>
          <%= f.collection_select(:artikelgroep_id, Artikelgroep.where("ID in (?)",ag_ids), :id, :omschrijving) %>
    </div>
    <div class="actions">
      <%= f.submit yield(:rio_action) %>
    </div>
<% end %>

app/views/artikels/_regel.html.erb
<td><%= artikel.artikelnummer %></td>
<td><%= artikel.omschrijving %></td>
<td><%= toon_prijs(artikel.prijs) %></td>
<td><%= artikel.ag_omschrijving %></td>
<% if crud.include? 'R'  %>
    <td><%= link_to 'Show', artikel %></td>
<% else %>
    <td></td>
<% end %>
<% if crud.include? 'U' %>
    <td><%= link_to 'Edit', edit_artikel_path(artikel) %></td>
<% else %>
    <td></td>
<% end %>
<% if crud.include? 'D' %>
    <td><%= link_to 'Destroy', artikel, method: :delete, data: {confirm: 'Are you sure?'} %></td>
<% else %>
    <td></td>
<% end %>

app/views/artikels/edit.html.erb
<% provide(:title, "Edit artikel") %>
<% provide(:rio_action, "Edit artikel") %>
<h1>Edit artikel</h1>
<%= render :partial =>'form' , :locals => { :ag_ids=>Artikelgroep.user_may_update(current_user.id)}  %>
<%= link_to 'Show', @artikel %> |
<%= link_to 'Back', artikels_path %>

app/views/artikels/index.html.erb
<h1>Overzicht Artikelen</h1>

<%= form_tag artikels_path, method: 'get' , class: "field" do %>
    <p>
     <%= text_field_tag :search,  params[:search], class: "artikels_search   size10" %>
     <%= submit_tag "Zoeken", name: nil %>
    </p>
<% end %>
<div class="artikel_1"></div>
<table>
  <thead>
  <tr>
    <th>Artikelnummer</th>
    <th>Name</th>
    <th>Prijs</th>
    <th>Art groep</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @artikels.each do |artikel| %>
      <tr>
        <%= render :partial => "regel", :locals => {:artikel => artikel, :crud => crud_current_user(artikel.artikelgroep_id)} %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if user_has_any_create_artikel %>
    <%= link_to 'New Artikel', new_artikel_path %>
<% end %>

app/views/artikels/new.html.erb
<% provide(:title, "Nieuw artikel") %>
<% provide(:rio_action, "Voeg artikel toe") %>
<h1>New artikel</h1>

<%= render :partial =>'form' , :locals => { :ag_ids=>Artikelgroep.user_may_create(current_user.id)}  %>

<%= link_to 'Back', artikels_path %>

app/views/artikels/show.html.erb
<% provide(:title, "Toon artikel") %>

<p id="notice"><%= notice %></p>

<p>
  Test <%= @artikel.omschrijving %>

  <strong>Omschrijving:</strong>
  <%= @artikel.omschrijving %>
</p>

<p>
  <strong>Prijs:</strong>
  <%= toon_prijs(@artikel.prijs) %>
</p>

<p>
  <strong>Artikelgroep:</strong>
  <%= @artikel.ag_omschrijving %>
</p>

<% if user_may_update_artikel(@artikel.artikelgroep_id) %>
    <%= link_to 'Edit', edit_artikel_path(@artikel) %> |
<% end %>
<%= link_to 'Back', artikels_path %>